### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by momingh** [TangJiakai/RGCL#1]
Is this the code repository for the paper 'Towards Robust Recommendation via Decision Boundary-aware Graph Contrastive Learning'? When do you plan to publish the code

**Comment by TangJiakai** [comment]
Apologies, I will update the code link on the project homepage. The updated code link is as follows:
https://drive.google.com/file/d/1MV07_PK9GwfWUVBV-G9cAdHMso9XbC8q/view?usp=drive_link
